language: c

compiler:
  - clang
  - gcc

branches:
  only: revolution

notifications:
  email:
    on_success: never

install:
  - sudo apt-get install -qq build-essential

script:
  - make
  - test/test.sh